//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailClassesSender.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailClassesSender.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;NetWorker Professional&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;width:100%;&quot; align=&quot;center&quot;&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td align=&quot;center&quot; valign=&quot;top&quot; style=&quot;background-color:#53636e;&quot; bgcolor=&quot;#53636e;&quot;&gt;   
        ///    &lt;br&gt;
        ///    &lt;br&gt;
        ///    &lt;table width=&quot;583&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///      &lt;tr&gt;
        ///        &lt;td align=&quot;left [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetWorkerGlobalMailBody {
            get {
                return ResourceManager.GetString("NetWorkerGlobalMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global@networkerprofessional.net.
        /// </summary>
        internal static string NetWorkerGlobalMailFrom {
            get {
                return ResourceManager.GetString("NetWorkerGlobalMailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarcoJon749#01.
        /// </summary>
        internal static string NetWorkerGlobalMailPassword {
            get {
                return ResourceManager.GetString("NetWorkerGlobalMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de Información.
        /// </summary>
        internal static string NetWorkerGlobalMailSubject {
            get {
                return ResourceManager.GetString("NetWorkerGlobalMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NetWorkerLogo {
            get {
                object obj = ResourceManager.GetObject("NetWorkerLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.networkerprofessional.net.
        /// </summary>
        internal static string NetWorkerMailHost {
            get {
                return ResourceManager.GetString("NetWorkerMailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;NetWorker Professional&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;width:100%;&quot; align=&quot;center&quot;&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td align=&quot;center&quot; valign=&quot;top&quot; style=&quot;background-color:#53636e;&quot; bgcolor=&quot;#53636e;&quot;&gt;   
        ///    &lt;br&gt;
        ///    &lt;br&gt;
        ///    &lt;table width=&quot;583&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///      &lt;tr&gt;
        ///        &lt;td align=&quot;left [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetWorkerNewUserMailBody {
            get {
                return ResourceManager.GetString("NetWorkerNewUserMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a NetWorker Professional.
        /// </summary>
        internal static string NetWorkerNewUserMailSubject {
            get {
                return ResourceManager.GetString("NetWorkerNewUserMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;NetWorker Professional&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;width:100%;&quot; align=&quot;center&quot;&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td align=&quot;center&quot; valign=&quot;top&quot; style=&quot;background-color:#53636e;&quot; bgcolor=&quot;#53636e;&quot;&gt;   
        ///    &lt;br&gt;
        ///    &lt;br&gt;
        ///    &lt;table width=&quot;583&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///      &lt;tr&gt;
        ///        &lt;td align=&quot;left [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetWorkerPersonalMailBody {
            get {
                return ResourceManager.GetString("NetWorkerPersonalMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;NetWorker Professional&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;width:100%;&quot; align=&quot;center&quot;&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td align=&quot;center&quot; valign=&quot;top&quot; style=&quot;background-color:#53636e;&quot; bgcolor=&quot;#53636e;&quot;&gt;   
        ///    &lt;br&gt;
        ///    &lt;br&gt;
        ///    &lt;table width=&quot;583&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///      &lt;tr&gt;
        ///        &lt;td align=&quot;left [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetWorkerSupportMailBody {
            get {
                return ResourceManager.GetString("NetWorkerSupportMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@networkerprofessional.net.
        /// </summary>
        internal static string NetWorkerSupportMailFrom {
            get {
                return ResourceManager.GetString("NetWorkerSupportMailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarcoJon749#01.
        /// </summary>
        internal static string NetWorkerSupportMailPassword {
            get {
                return ResourceManager.GetString("NetWorkerSupportMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva cuenta NetWorker Professional.
        /// </summary>
        internal static string NetWorkerSupportMailSubject {
            get {
                return ResourceManager.GetString("NetWorkerSupportMailSubject", resourceCulture);
            }
        }
    }
}
